### ISSUE TITLE
error

### ISSUE THREAD

**Issue by RandomAltThing** [KsyMC/MCPE-addons#9]
I get 3 errors with TestAddon

**Comment by KsyMC** [comment]
What error?

**Comment by ManassehPierce** [comment]
http://imgur.com/bCdgTgZ
http://imgur.com/4O0NsVX
Here they are ^^ Please fix asap, I am really interested in addons, thank you for your time

**Comment by jose-vm** [comment]
@ManassehPierce TestAddon should be compiled with the NDK. You need to do some optimizations to compile it in AIDE.
